### ISSUE TITLE
Simulated Annealing in MH algorithm

### ISSUE THREAD

**Issue by PhyloStar** [PhyloStar/CyBayes#13]
@robertostling Does it make sense to anneal the likelihood during burnin? I googled around a bit. But did not find much literature. My idea is to anneal the likelihood from low temperature to high temperature during burnin and then sample sample at high temperature for the rest of the chain.

**Comment by robertostling** [comment]
@PhyloStar From low temperature to high temperature, i.e. going from less randomness to more randomness? Do you mean the other way around, or what would be the intuition behind that?

I also did annealing (high to low, starting with a high-entropy distribution closer to uniform and slowly moving towards the actual distribution) during burn-in, as a way for the chain to move quickly to a reasonably high-probability area, which can then be sampled from at a low temperature.

I guess if the chain actually converges this won't matter, but we're both working with slow-moving chains (right?) and we're never going to get enough samples, so the only question is if you want to get too few samples from a bad part of the space or too few samples from a better part of the space. And if annealing during burn-in gets you to a better place, go for it.

**Comment by PhyloStar** [comment]
@robertostling You are right. I meant from high temperature to low temperature so that the chain starts to sample from likelihood with temperature 1 after some initial burnin.

The chain is really slow. If I use bold proposals that make lot of changes, then, the chain does not mix well. If use the bold proposals at slow rate, then, the chain is stuck at some point for a lot of time.

I am thinking of a schedule that is 1/(B-b) where B is the number of states to perform annealing. and 0 <= b < B. Do you have any better schedule idea?

**Comment by robertostling** [comment]
@PhyloStar I used a simple linear increase of the annealing exponent lambda (inverse temperature) = k*t after t samples, where k > 0 is the rate of cooling. At t -> inf, you're doing greedy search, which is also worth trying. Especially if it's difficult to compute marginal distributions from samples, you could just end with a greedy search and use the final "sample". This might not be ideal, but I don't know any systematic investigation of. I tried some variants for the aligner, and didn't find anything much better.

Not sure what you mean by "number of states to perform annealing".

**Comment by PhyloStar** [comment]
I tried this. For a short period of states B in the chain, anneal exponent is 1.0+k*(B-n_iter). k is fixed at 0.0001. 

Once the chain reaches B generations, the temperature is 1 and the chain samples from cold chain. Seems to work as the chain moves from a inverse temperature of 0.25 to 1.0. After that I am doing regular MCMC.

**Comment by PhyloStar** [comment]
There is another issue running on parallel tempering which will go on.
