### ISSUE TITLE
Cython Blas vs numpy dot

### ISSUE THREAD

**Issue by PhyloStar** [PhyloStar/CyBayes#24]
@robertostling I am using numpy's dot multiplication to multiply a KxK matrix with a KxS matrix. K is in the range of 2 to 40 whereas S is in the range of 500 to 10000. The dot product is the main bottleneck since most of the calls are here:
https://github.com/PhyloStar/CyBayes/blob/a1dc917ac53a6c6c02df2d6732dcb4ebb8b67f92/ML_gamma.pyx#L25

I am directly calling the numpy dot within Cython. Do you think directly calling BLAS function matrix multiplication would be faster? If I can bring the cost down then it would be great since direct calling might be faster.

**Comment by robertostling** [comment]
Sorry, I don't know enough numpy internals to answer this, but my guess would be that unless you store the matrices in some BLAS-unfriendly format that needs to be converted, the overhead shouldn't be that great compared to the actual computations done.

One thing that does matter (though not sure how much for the smallish matrices you have) is the BLAS implementation, in some cases MKL can make a big difference.

**Comment by PhyloStar** [comment]
Is there any ubuntu specific MKL numpy that can be pip installed you recommend?

**Comment by robertostling** [comment]
I installed MKL, then compiled numpy (on Debian, and iirc I had to change some paths). There is an Intel-bundled version of MKL+numpy that might work for you, but I didn't try that.
