### ISSUE TITLE
Faster matrix multiplications

### ISSUE THREAD

**Issue by PhyloStar** [PhyloStar/CyBayes#3]
Will need faster matrix multiplications since the profiling suggests that most of the time is spent in computing matrix multiplications which are part of numpy dot function. Is there any way to optimize it @anaphory.

I tried tests with cython's blas wrapper with dgemm function. But the timing results are not better than np.dot function. Any feedback is welcome.

**Comment by Anaphory** [comment]
Matrix multiplication *is* expensive. I assume the matrices you multiply are exponentials of rate matrices, so they are also not sparse?

**Comment by PhyloStar** [comment]
The probability matrices are not sparse. For a single language, I am treating all the sites as a single matrix and then perform matrix multiplication. In case of binary states with 2000 sites it would mean a 2X2000 matrix of 1s and 0s. This matrix is left multiplied by a 2X2 probability matrix to give the marginal probabilities at the parent node of a leaf.

**Comment by PhyloStar** [comment]
I dont think there is any better than I have here using numpy dot products using OpenBLAS. I would like to benchmark it against MKL. But, I dont have a numpy setup compiled using MKL. So, closing the issue.
