### ISSUE TITLE
Multiple aligned datasets

### ISSUE THREAD

**Issue by PhyloStar** [PhyloStar/CyBayes#5]
Multiple aligned datasets with preferably SCA/ASJP encoding might be useful for testing the phylogenies. Of course, we are interested in checking how the trees emerge from the runs. @anaphory has some datasets that have small alphabet size to test.

@LinguList Shall I assign this to you?

**Comment by LinguList** [comment]
Question is what you want: do you want me to convert data to some
SCA/ASJP format and align it automatically, illustrating how this would
work in lingpy, and maybe pointing to those cases where you could re-use
the lingpy code, or should I submit the testset itself?

**Comment by PhyloStar** [comment]
The first one is really nice since that allows me to add to the wiki that one can generate aligned datasets using LingPy and can generate trees using CyBayes.

**Comment by LinguList** [comment]
okay, then give me a dataset, and I'll see to add some code later next week, potentially.

**Comment by PhyloStar** [comment]
Thanks to @LinguList who wrote the main code to align sequences and convert to SCA. I added align_data.py file that can take a word list such as `data/Chinese-180-18.tsv` and convert to `data/Chinese-180-18.prog.phy` that can be processed by CyBayes.

**Comment by PhyloStar** [comment]
Thanks to @LinguList who wrote the main code to align sequences and convert to SCA. I added align_data.py file that can take a word list such as `data/Chinese-180-18.tsv`
 and convert to `data/Chinese-180-18.prog.phy` that can be processed by CyBayes.

I added IELex.tsv, Mayan.tsv, and Mixe-Zoque.tsv and the corresponding progressive aligned files for tree inference.
