### ISSUE TITLE
Add entry points to setup.py script

### ISSUE THREAD

**Issue by LinguList** [PhyloStar/CyBayes#54]
To make cybayes available via command line, you have to add entry points to the setup.py. 

```python
setup(
    ...
    entry_points={"console_scripts": ["cybaymcmc=cybayes.mcmc"],
)
```

This allows you to call it later via commandline:

```
$ cybaymcmc --help
```

**Comment by PhyloStar** [comment]
I am running the file `st_cache.py` for our purpose. The command line argument is `python3 st_cache.py -i allenbai.nex -m F81 -d bin`. I renamed the `st_cache.py` to `cybaymcmc.py`.

I edited the `setup,py` file as you suggested. One question is should i move the Python code to a different folder like `mcmc` within `CyBayes` and place the setup.py parallel to `mcmc`?

**Comment by LinguList** [comment]
The best way to proceed is:

* `src/cybayes/` contains all code 

The setup.py needs to be adjusted, but you can find examples for `github.com/concepticon/pyconcepticon/` or `lingpy/lingrex`. 

THEN, you have two possibilities. Either one commandline script only, and you call it as you want (no need to rename the file, place the file inside the `src/cybayes`. OR, and this is what we do in `cldfbench`, etc.: one folder inside `src/cybayes`, called `commands`, and each script in this folder can be executed if you type `cybayes command`. This is probably even better (!). 

In general, I think, you start by moving all to `src/cybayes/commands`. 

You should also consider making a fresh repository by making a new organization `cybayes` or `pybayes`, as it is easier to make a fresh start, since by now there are many files with code snippets, probably not needed?

**Comment by LinguList** [comment]
BTW: I made a first organization etc. and I suggest to start [here](https://github.com/pylogeny/bayes). I will also add `pylogeny/distance` where I can port my NJ code etc. from LingPy. In this way, the `pylogeny` can become something like phylip in Python: many small packages, all devoted to some aspect of phylogeny computation in Python...
